# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCredential1password < Formula
  desc "Helper to store git credentials inside 1password."
  homepage "https://github.com/develerik/homebrew-tools"
  version "1.1.1"
  license "ISC"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/develerik/git-credential-1password/releases/download/v1.1.1/git-credential-1password_1.1.1_darwin_arm64.tar.gz"
      sha256 "60e97235b806628dc56cfb4f8a7b1d3642d9ee8e387348ab60dd298245d92d1b"

      def install
        bin.install "git-credential-1password"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/develerik/git-credential-1password/releases/download/v1.1.1/git-credential-1password_1.1.1_darwin_amd64.tar.gz"
      sha256 "f72012b435e7eba01da6bd5b347ed548cd856d9716b0641109c0f6822bc2a866"

      def install
        bin.install "git-credential-1password"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/develerik/git-credential-1password/releases/download/v1.1.1/git-credential-1password_1.1.1_linux_arm64.tar.gz"
      sha256 "33067ded5abbf982cb78a813aef94fda9b9b9b08976e5cfc9502876637b2a64c"

      def install
        bin.install "git-credential-1password"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/develerik/git-credential-1password/releases/download/v1.1.1/git-credential-1password_1.1.1_linux_amd64.tar.gz"
      sha256 "620d7695c4e052dcb6e4e96903f5ef75a95e1e60402840c7c3a22f5de72615c7"

      def install
        bin.install "git-credential-1password"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/develerik/git-credential-1password/releases/download/v1.1.1/git-credential-1password_1.1.1_linux_armv6.tar.gz"
      sha256 "b3b502e4bc18f7ebf19d5d3bcad7dc0da3c0c807e271ccae4d8c422add230d0f"

      def install
        bin.install "git-credential-1password"
      end
    end
  end

  depends_on "git"
end
